// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkStatus int32

const (
	ChunkStatus_CHUNK_STATUS_UNKNOWN   ChunkStatus = 0
	ChunkStatus_CHUNK_STATUS_PENDING   ChunkStatus = 1
	ChunkStatus_CHUNK_STATUS_COMPLETE  ChunkStatus = 2
	ChunkStatus_CHUNK_STATUS_FAILED    ChunkStatus = 3
	ChunkStatus_CHUNK_STATUS_NOT_FOUND ChunkStatus = 4
)

// Enum value maps for ChunkStatus.
var (
	ChunkStatus_name = map[int32]string{
		0: "CHUNK_STATUS_UNKNOWN",
		1: "CHUNK_STATUS_PENDING",
		2: "CHUNK_STATUS_COMPLETE",
		3: "CHUNK_STATUS_FAILED",
		4: "CHUNK_STATUS_NOT_FOUND",
	}
	ChunkStatus_value = map[string]int32{
		"CHUNK_STATUS_UNKNOWN":   0,
		"CHUNK_STATUS_PENDING":   1,
		"CHUNK_STATUS_COMPLETE":  2,
		"CHUNK_STATUS_FAILED":    3,
		"CHUNK_STATUS_NOT_FOUND": 4,
	}
)

func (x ChunkStatus) Enum() *ChunkStatus {
	p := new(ChunkStatus)
	*p = x
	return p
}

func (x ChunkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[0].Descriptor()
}

func (ChunkStatus) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[0]
}

func (x ChunkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkStatus.Descriptor instead.
func (ChunkStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChunkResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FileId            string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex        int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TelegramFileId    string                 `protobuf:"bytes,3,opt,name=telegram_file_id,json=telegramFileId,proto3" json:"telegram_file_id,omitempty"`
	TelegramMessageId int32                  `protobuf:"varint,4,opt,name=telegram_message_id,json=telegramMessageId,proto3" json:"telegram_message_id,omitempty"`
	BotId             int64                  `protobuf:"varint,5,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	EncryptionIv      string                 `protobuf:"bytes,6,opt,name=encryption_iv,json=encryptionIv,proto3" json:"encryption_iv,omitempty"`
	Size              int32                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Etag              string                 `protobuf:"bytes,8,opt,name=etag,proto3" json:"etag,omitempty"`
	ChunkId           string                 `protobuf:"bytes,9,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChunkResult) Reset() {
	*x = ChunkResult{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResult) ProtoMessage() {}

func (x *ChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResult.ProtoReflect.Descriptor instead.
func (*ChunkResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChunkResult) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkResult) GetTelegramFileId() string {
	if x != nil {
		return x.TelegramFileId
	}
	return ""
}

func (x *ChunkResult) GetTelegramMessageId() int32 {
	if x != nil {
		return x.TelegramMessageId
	}
	return 0
}

func (x *ChunkResult) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *ChunkResult) GetEncryptionIv() string {
	if x != nil {
		return x.EncryptionIv
	}
	return ""
}

func (x *ChunkResult) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkResult) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ChunkResult) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type ReportChunkResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ChunkResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChunkResultsRequest) Reset() {
	*x = ReportChunkResultsRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChunkResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChunkResultsRequest) ProtoMessage() {}

func (x *ReportChunkResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChunkResultsRequest.ProtoReflect.Descriptor instead.
func (*ReportChunkResultsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *ReportChunkResultsRequest) GetResults() []*ChunkResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReportChunkResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChunkResultsResponse) Reset() {
	*x = ReportChunkResultsResponse{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChunkResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChunkResultsResponse) ProtoMessage() {}

func (x *ReportChunkResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChunkResultsResponse.ProtoReflect.Descriptor instead.
func (*ReportChunkResultsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *ReportChunkResultsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type GetFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileMetadataRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ChunkMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex        int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Size              int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TelegramFileId    string                 `protobuf:"bytes,3,opt,name=telegram_file_id,json=telegramFileId,proto3" json:"telegram_file_id,omitempty"`
	TelegramMessageId int32                  `protobuf:"varint,4,opt,name=telegram_message_id,json=telegramMessageId,proto3" json:"telegram_message_id,omitempty"`
	BotId             int64                  `protobuf:"varint,5,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	EncryptionIv      string                 `protobuf:"bytes,6,opt,name=encryption_iv,json=encryptionIv,proto3" json:"encryption_iv,omitempty"`
	Etag              string                 `protobuf:"bytes,7,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChunkMetadata) Reset() {
	*x = ChunkMetadata{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMetadata) ProtoMessage() {}

func (x *ChunkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMetadata.ProtoReflect.Descriptor instead.
func (*ChunkMetadata) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkMetadata) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkMetadata) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkMetadata) GetTelegramFileId() string {
	if x != nil {
		return x.TelegramFileId
	}
	return ""
}

func (x *ChunkMetadata) GetTelegramMessageId() int32 {
	if x != nil {
		return x.TelegramMessageId
	}
	return 0
}

func (x *ChunkMetadata) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *ChunkMetadata) GetEncryptionIv() string {
	if x != nil {
		return x.EncryptionIv
	}
	return ""
}

func (x *ChunkMetadata) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type FileMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Size               int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MimeType           string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Filename           string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	IsEncrypted        bool                   `protobuf:"varint,10,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptionAlgo     string                 `protobuf:"bytes,11,opt,name=encryption_algo,json=encryptionAlgo,proto3" json:"encryption_algo,omitempty"`
	EncryptionIv       string                 `protobuf:"bytes,12,opt,name=encryption_iv,json=encryptionIv,proto3" json:"encryption_iv,omitempty"`
	EncryptedKey       string                 `protobuf:"bytes,13,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	BotId              int64                  `protobuf:"varint,20,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	IsChunked          bool                   `protobuf:"varint,21,opt,name=is_chunked,json=isChunked,proto3" json:"is_chunked,omitempty"`
	TelegramFileId     string                 `protobuf:"bytes,22,opt,name=telegram_file_id,json=telegramFileId,proto3" json:"telegram_file_id,omitempty"`
	TelegramMessageId  int32                  `protobuf:"varint,23,opt,name=telegram_message_id,json=telegramMessageId,proto3" json:"telegram_message_id,omitempty"`
	TotalChunks        int32                  `protobuf:"varint,24,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Chunks             []*ChunkMetadata       `protobuf:"bytes,25,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Status             string                 `protobuf:"bytes,30,opt,name=status,proto3" json:"status,omitempty"`
	Visibility         string                 `protobuf:"bytes,31,opt,name=visibility,proto3" json:"visibility,omitempty"`
	DownloadLimit_24H  int32                  `protobuf:"varint,40,opt,name=download_limit_24h,json=downloadLimit24h,proto3" json:"download_limit_24h,omitempty"`
	Downloads_24H      int32                  `protobuf:"varint,41,opt,name=downloads_24h,json=downloads24h,proto3" json:"downloads_24h,omitempty"`
	BandwidthLimit_24H int64                  `protobuf:"varint,42,opt,name=bandwidth_limit_24h,json=bandwidthLimit24h,proto3" json:"bandwidth_limit_24h,omitempty"`
	BandwidthUsed_24H  int64                  `protobuf:"varint,43,opt,name=bandwidth_used_24h,json=bandwidthUsed24h,proto3" json:"bandwidth_used_24h,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *FileMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *FileMetadata) GetEncryptionAlgo() string {
	if x != nil {
		return x.EncryptionAlgo
	}
	return ""
}

func (x *FileMetadata) GetEncryptionIv() string {
	if x != nil {
		return x.EncryptionIv
	}
	return ""
}

func (x *FileMetadata) GetEncryptedKey() string {
	if x != nil {
		return x.EncryptedKey
	}
	return ""
}

func (x *FileMetadata) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *FileMetadata) GetIsChunked() bool {
	if x != nil {
		return x.IsChunked
	}
	return false
}

func (x *FileMetadata) GetTelegramFileId() string {
	if x != nil {
		return x.TelegramFileId
	}
	return ""
}

func (x *FileMetadata) GetTelegramMessageId() int32 {
	if x != nil {
		return x.TelegramMessageId
	}
	return 0
}

func (x *FileMetadata) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileMetadata) GetChunks() []*ChunkMetadata {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *FileMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileMetadata) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *FileMetadata) GetDownloadLimit_24H() int32 {
	if x != nil {
		return x.DownloadLimit_24H
	}
	return 0
}

func (x *FileMetadata) GetDownloads_24H() int32 {
	if x != nil {
		return x.Downloads_24H
	}
	return 0
}

func (x *FileMetadata) GetBandwidthLimit_24H() int64 {
	if x != nil {
		return x.BandwidthLimit_24H
	}
	return 0
}

func (x *FileMetadata) GetBandwidthUsed_24H() int64 {
	if x != nil {
		return x.BandwidthUsed_24H
	}
	return 0
}

type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIds       []string               `protobuf:"bytes,1,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCheckRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type ChunkStatusEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Status        ChunkStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=core.ChunkStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkStatusEntry) Reset() {
	*x = ChunkStatusEntry{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkStatusEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkStatusEntry) ProtoMessage() {}

func (x *ChunkStatusEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkStatusEntry.ProtoReflect.Descriptor instead.
func (*ChunkStatusEntry) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkStatusEntry) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChunkStatusEntry) GetStatus() ChunkStatus {
	if x != nil {
		return x.Status
	}
	return ChunkStatus_CHUNK_STATUS_UNKNOWN
}

type BatchCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ChunkStatusEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *BatchCheckResponse) GetEntries() []*ChunkStatusEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReportUploadFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	IsChunk       bool                   `protobuf:"varint,4,opt,name=is_chunk,json=isChunk,proto3" json:"is_chunk,omitempty"`
	ChunkId       string                 `protobuf:"bytes,5,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUploadFailedRequest) Reset() {
	*x = ReportUploadFailedRequest{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUploadFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUploadFailedRequest) ProtoMessage() {}

func (x *ReportUploadFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUploadFailedRequest.ProtoReflect.Descriptor instead.
func (*ReportUploadFailedRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *ReportUploadFailedRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ReportUploadFailedRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ReportUploadFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportUploadFailedRequest) GetIsChunk() bool {
	if x != nil {
		return x.IsChunk
	}
	return false
}

func (x *ReportUploadFailedRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type ReportDeleteSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDeleteSuccessRequest) Reset() {
	*x = ReportDeleteSuccessRequest{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDeleteSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDeleteSuccessRequest) ProtoMessage() {}

func (x *ReportDeleteSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDeleteSuccessRequest.ProtoReflect.Descriptor instead.
func (*ReportDeleteSuccessRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *ReportDeleteSuccessRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ReportDeleteFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDeleteFailedRequest) Reset() {
	*x = ReportDeleteFailedRequest{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDeleteFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDeleteFailedRequest) ProtoMessage() {}

func (x *ReportDeleteFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDeleteFailedRequest.ProtoReflect.Descriptor instead.
func (*ReportDeleteFailedRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *ReportDeleteFailedRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ReportDeleteFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReportFileCorruptedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileId         string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	TelegramFileId string                 `protobuf:"bytes,2,opt,name=telegram_file_id,json=telegramFileId,proto3" json:"telegram_file_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportFileCorruptedRequest) Reset() {
	*x = ReportFileCorruptedRequest{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFileCorruptedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFileCorruptedRequest) ProtoMessage() {}

func (x *ReportFileCorruptedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFileCorruptedRequest.ProtoReflect.Descriptor instead.
func (*ReportFileCorruptedRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *ReportFileCorruptedRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ReportFileCorruptedRequest) GetTelegramFileId() string {
	if x != nil {
		return x.TelegramFileId
	}
	return ""
}

type ZipPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZipPart) Reset() {
	*x = ZipPart{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZipPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZipPart) ProtoMessage() {}

func (x *ZipPart) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZipPart.ProtoReflect.Descriptor instead.
func (*ZipPart) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *ZipPart) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZipPart) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ZipPart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ReportZipReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Parts         []*ZipPart             `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Streaming     bool                   `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportZipReadyRequest) Reset() {
	*x = ReportZipReadyRequest{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportZipReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportZipReadyRequest) ProtoMessage() {}

func (x *ReportZipReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportZipReadyRequest.ProtoReflect.Descriptor instead.
func (*ReportZipReadyRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *ReportZipReadyRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportZipReadyRequest) GetParts() []*ZipPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *ReportZipReadyRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ReportZipReadyRequest) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

type ReportZipFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportZipFailedRequest) Reset() {
	*x = ReportZipFailedRequest{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportZipFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportZipFailedRequest) ProtoMessage() {}

func (x *ReportZipFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportZipFailedRequest.ProtoReflect.Descriptor instead.
func (*ReportZipFailedRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *ReportZipFailedRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportZipFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReportBotUnauthorizedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportBotUnauthorizedRequest) Reset() {
	*x = ReportBotUnauthorizedRequest{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBotUnauthorizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBotUnauthorizedRequest) ProtoMessage() {}

func (x *ReportBotUnauthorizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBotUnauthorizedRequest.ProtoReflect.Descriptor instead.
func (*ReportBotUnauthorizedRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *ReportBotUnauthorizedRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type ReportEmergencyCleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIds       []string               `protobuf:"bytes,1,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEmergencyCleanupRequest) Reset() {
	*x = ReportEmergencyCleanupRequest{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEmergencyCleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEmergencyCleanupRequest) ProtoMessage() {}

func (x *ReportEmergencyCleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEmergencyCleanupRequest.ProtoReflect.Descriptor instead.
func (*ReportEmergencyCleanupRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *ReportEmergencyCleanupRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type DiskSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreeBytes     int64                  `protobuf:"varint,1,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsagePercent  float64                `protobuf:"fixed64,3,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSpaceResponse) Reset() {
	*x = DiskSpaceResponse{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSpaceResponse) ProtoMessage() {}

func (x *DiskSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSpaceResponse.ProtoReflect.Descriptor instead.
func (*DiskSpaceResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *DiskSpaceResponse) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskSpaceResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskSpaceResponse) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type ReportCronStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CronName       string                 `protobuf:"bytes,1,opt,name=cron_name,json=cronName,proto3" json:"cron_name,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,2,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	FreedBytes     int64                  `protobuf:"varint,3,opt,name=freed_bytes,json=freedBytes,proto3" json:"freed_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportCronStatsRequest) Reset() {
	*x = ReportCronStatsRequest{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCronStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCronStatsRequest) ProtoMessage() {}

func (x *ReportCronStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCronStatsRequest.ProtoReflect.Descriptor instead.
func (*ReportCronStatsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *ReportCronStatsRequest) GetCronName() string {
	if x != nil {
		return x.CronName
	}
	return ""
}

func (x *ReportCronStatsRequest) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *ReportCronStatsRequest) GetFreedBytes() int64 {
	if x != nil {
		return x.FreedBytes
	}
	return 0
}

type VerifyFolderShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyFolderShareRequest) Reset() {
	*x = VerifyFolderShareRequest{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyFolderShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFolderShareRequest) ProtoMessage() {}

func (x *VerifyFolderShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFolderShareRequest.ProtoReflect.Descriptor instead.
func (*VerifyFolderShareRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *VerifyFolderShareRequest) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

func (x *VerifyFolderShareRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type VerifyFolderShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyFolderShareResponse) Reset() {
	*x = VerifyFolderShareResponse{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyFolderShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFolderShareResponse) ProtoMessage() {}

func (x *VerifyFolderShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFolderShareResponse.ProtoReflect.Descriptor instead.
func (*VerifyFolderShareResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

func (x *VerifyFolderShareResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\"\a\n" +
	"\x05Empty\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xa0\x02\n" +
	"\vChunkResult\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12(\n" +
	"\x10telegram_file_id\x18\x03 \x01(\tR\x0etelegramFileId\x12.\n" +
	"\x13telegram_message_id\x18\x04 \x01(\x05R\x11telegramMessageId\x12\x15\n" +
	"\x06bot_id\x18\x05 \x01(\x03R\x05botId\x12#\n" +
	"\rencryption_iv\x18\x06 \x01(\tR\fencryptionIv\x12\x12\n" +
	"\x04size\x18\a \x01(\x05R\x04size\x12\x12\n" +
	"\x04etag\x18\b \x01(\tR\x04etag\x12\x19\n" +
	"\bchunk_id\x18\t \x01(\tR\achunkId\"H\n" +
	"\x19ReportChunkResultsRequest\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.core.ChunkResultR\aresults\"8\n" +
	"\x1aReportChunkResultsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\"1\n" +
	"\x16GetFileMetadataRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\xee\x01\n" +
	"\rChunkMetadata\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12(\n" +
	"\x10telegram_file_id\x18\x03 \x01(\tR\x0etelegramFileId\x12.\n" +
	"\x13telegram_message_id\x18\x04 \x01(\x05R\x11telegramMessageId\x12\x15\n" +
	"\x06bot_id\x18\x05 \x01(\x03R\x05botId\x12#\n" +
	"\rencryption_iv\x18\x06 \x01(\tR\fencryptionIv\x12\x12\n" +
	"\x04etag\x18\a \x01(\tR\x04etag\"\xe3\x05\n" +
	"\fFileMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12!\n" +
	"\fis_encrypted\x18\n" +
	" \x01(\bR\visEncrypted\x12'\n" +
	"\x0fencryption_algo\x18\v \x01(\tR\x0eencryptionAlgo\x12#\n" +
	"\rencryption_iv\x18\f \x01(\tR\fencryptionIv\x12#\n" +
	"\rencrypted_key\x18\r \x01(\tR\fencryptedKey\x12\x15\n" +
	"\x06bot_id\x18\x14 \x01(\x03R\x05botId\x12\x1d\n" +
	"\n" +
	"is_chunked\x18\x15 \x01(\bR\tisChunked\x12(\n" +
	"\x10telegram_file_id\x18\x16 \x01(\tR\x0etelegramFileId\x12.\n" +
	"\x13telegram_message_id\x18\x17 \x01(\x05R\x11telegramMessageId\x12!\n" +
	"\ftotal_chunks\x18\x18 \x01(\x05R\vtotalChunks\x12+\n" +
	"\x06chunks\x18\x19 \x03(\v2\x13.core.ChunkMetadataR\x06chunks\x12\x16\n" +
	"\x06status\x18\x1e \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\x1f \x01(\tR\n" +
	"visibility\x12,\n" +
	"\x12download_limit_24h\x18( \x01(\x05R\x10downloadLimit24h\x12#\n" +
	"\rdownloads_24h\x18) \x01(\x05R\fdownloads24h\x12.\n" +
	"\x13bandwidth_limit_24h\x18* \x01(\x03R\x11bandwidthLimit24h\x12,\n" +
	"\x12bandwidth_used_24h\x18+ \x01(\x03R\x10bandwidthUsed24h\".\n" +
	"\x11BatchCheckRequest\x12\x19\n" +
	"\bfile_ids\x18\x01 \x03(\tR\afileIds\"V\n" +
	"\x10ChunkStatusEntry\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.core.ChunkStatusR\x06status\"F\n" +
	"\x12BatchCheckResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.core.ChunkStatusEntryR\aentries\"\xa3\x01\n" +
	"\x19ReportUploadFailedRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\bis_chunk\x18\x04 \x01(\bR\aisChunk\x12\x19\n" +
	"\bchunk_id\x18\x05 \x01(\tR\achunkId\"5\n" +
	"\x1aReportDeleteSuccessRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"L\n" +
	"\x19ReportDeleteFailedRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"_\n" +
	"\x1aReportFileCorruptedRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12(\n" +
	"\x10telegram_file_id\x18\x02 \x01(\tR\x0etelegramFileId\"E\n" +
	"\aZipPart\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"\x90\x01\n" +
	"\x15ReportZipReadyRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\x05parts\x18\x02 \x03(\v2\r.core.ZipPartR\x05parts\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\"G\n" +
	"\x16ReportZipFailedRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"5\n" +
	"\x1cReportBotUnauthorizedRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\":\n" +
	"\x1dReportEmergencyCleanupRequest\x12\x19\n" +
	"\bfile_ids\x18\x01 \x03(\tR\afileIds\"x\n" +
	"\x11DiskSpaceResponse\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x01 \x01(\x03R\tfreeBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12#\n" +
	"\rusage_percent\x18\x03 \x01(\x01R\fusagePercent\"\x7f\n" +
	"\x16ReportCronStatsRequest\x12\x1b\n" +
	"\tcron_name\x18\x01 \x01(\tR\bcronName\x12'\n" +
	"\x0fprocessed_count\x18\x02 \x01(\x05R\x0eprocessedCount\x12\x1f\n" +
	"\vfreed_bytes\x18\x03 \x01(\x03R\n" +
	"freedBytes\"T\n" +
	"\x18VerifyFolderShareRequest\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"6\n" +
	"\x19VerifyFolderShareResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid*\x91\x01\n" +
	"\vChunkStatus\x12\x18\n" +
	"\x14CHUNK_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CHUNK_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15CHUNK_STATUS_COMPLETE\x10\x02\x12\x17\n" +
	"\x13CHUNK_STATUS_FAILED\x10\x03\x12\x1a\n" +
	"\x16CHUNK_STATUS_NOT_FOUND\x10\x042\x88\b\n" +
	"\vCoreService\x12W\n" +
	"\x12ReportChunkResults\x12\x1f.core.ReportChunkResultsRequest\x1a .core.ReportChunkResultsResponse\x12C\n" +
	"\x0fGetFileMetadata\x12\x1c.core.GetFileMetadataRequest\x1a\x12.core.FileMetadata\x12J\n" +
	"\x15BatchCheckChunkStatus\x12\x17.core.BatchCheckRequest\x1a\x18.core.BatchCheckResponse\x12B\n" +
	"\x12ReportUploadFailed\x12\x1f.core.ReportUploadFailedRequest\x1a\v.core.Empty\x12D\n" +
	"\x13ReportDeleteSuccess\x12 .core.ReportDeleteSuccessRequest\x1a\v.core.Empty\x12B\n" +
	"\x12ReportDeleteFailed\x12\x1f.core.ReportDeleteFailedRequest\x1a\v.core.Empty\x12D\n" +
	"\x13ReportFileCorrupted\x12 .core.ReportFileCorruptedRequest\x1a\v.core.Empty\x12:\n" +
	"\x0eReportZipReady\x12\x1b.core.ReportZipReadyRequest\x1a\v.core.Empty\x12<\n" +
	"\x0fReportZipFailed\x12\x1c.core.ReportZipFailedRequest\x1a\v.core.Empty\x12H\n" +
	"\x15ReportBotUnauthorized\x12\".core.ReportBotUnauthorizedRequest\x1a\v.core.Empty\x12J\n" +
	"\x16ReportEmergencyCleanup\x12#.core.ReportEmergencyCleanupRequest\x1a\v.core.Empty\x126\n" +
	"\x0eCheckDiskSpace\x12\v.core.Empty\x1a\x17.core.DiskSpaceResponse\x12<\n" +
	"\x0fReportCronStats\x12\x1c.core.ReportCronStatsRequest\x1a\v.core.Empty\x12T\n" +
	"\x11VerifyFolderShare\x12\x1e.core.VerifyFolderShareRequest\x1a\x1f.core.VerifyFolderShareResponse\x12\x1f\n" +
	"\x04Ping\x12\v.core.Empty\x1a\n" +
	".core.PongBGZEgithub.com/realldz/tele-drive/backend-transfer-go/internal/grpc/protob\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_core_proto_goTypes = []any{
	(ChunkStatus)(0),                      // 0: core.ChunkStatus
	(*Empty)(nil),                         // 1: core.Empty
	(*Pong)(nil),                          // 2: core.Pong
	(*ChunkResult)(nil),                   // 3: core.ChunkResult
	(*ReportChunkResultsRequest)(nil),     // 4: core.ReportChunkResultsRequest
	(*ReportChunkResultsResponse)(nil),    // 5: core.ReportChunkResultsResponse
	(*GetFileMetadataRequest)(nil),        // 6: core.GetFileMetadataRequest
	(*ChunkMetadata)(nil),                 // 7: core.ChunkMetadata
	(*FileMetadata)(nil),                  // 8: core.FileMetadata
	(*BatchCheckRequest)(nil),             // 9: core.BatchCheckRequest
	(*ChunkStatusEntry)(nil),              // 10: core.ChunkStatusEntry
	(*BatchCheckResponse)(nil),            // 11: core.BatchCheckResponse
	(*ReportUploadFailedRequest)(nil),     // 12: core.ReportUploadFailedRequest
	(*ReportDeleteSuccessRequest)(nil),    // 13: core.ReportDeleteSuccessRequest
	(*ReportDeleteFailedRequest)(nil),     // 14: core.ReportDeleteFailedRequest
	(*ReportFileCorruptedRequest)(nil),    // 15: core.ReportFileCorruptedRequest
	(*ZipPart)(nil),                       // 16: core.ZipPart
	(*ReportZipReadyRequest)(nil),         // 17: core.ReportZipReadyRequest
	(*ReportZipFailedRequest)(nil),        // 18: core.ReportZipFailedRequest
	(*ReportBotUnauthorizedRequest)(nil),  // 19: core.ReportBotUnauthorizedRequest
	(*ReportEmergencyCleanupRequest)(nil), // 20: core.ReportEmergencyCleanupRequest
	(*DiskSpaceResponse)(nil),             // 21: core.DiskSpaceResponse
	(*ReportCronStatsRequest)(nil),        // 22: core.ReportCronStatsRequest
	(*VerifyFolderShareRequest)(nil),      // 23: core.VerifyFolderShareRequest
	(*VerifyFolderShareResponse)(nil),     // 24: core.VerifyFolderShareResponse
}
var file_core_proto_depIdxs = []int32{
	3,  // 0: core.ReportChunkResultsRequest.results:type_name -> core.ChunkResult
	7,  // 1: core.FileMetadata.chunks:type_name -> core.ChunkMetadata
	0,  // 2: core.ChunkStatusEntry.status:type_name -> core.ChunkStatus
	10, // 3: core.BatchCheckResponse.entries:type_name -> core.ChunkStatusEntry
	16, // 4: core.ReportZipReadyRequest.parts:type_name -> core.ZipPart
	4,  // 5: core.CoreService.ReportChunkResults:input_type -> core.ReportChunkResultsRequest
	6,  // 6: core.CoreService.GetFileMetadata:input_type -> core.GetFileMetadataRequest
	9,  // 7: core.CoreService.BatchCheckChunkStatus:input_type -> core.BatchCheckRequest
	12, // 8: core.CoreService.ReportUploadFailed:input_type -> core.ReportUploadFailedRequest
	13, // 9: core.CoreService.ReportDeleteSuccess:input_type -> core.ReportDeleteSuccessRequest
	14, // 10: core.CoreService.ReportDeleteFailed:input_type -> core.ReportDeleteFailedRequest
	15, // 11: core.CoreService.ReportFileCorrupted:input_type -> core.ReportFileCorruptedRequest
	17, // 12: core.CoreService.ReportZipReady:input_type -> core.ReportZipReadyRequest
	18, // 13: core.CoreService.ReportZipFailed:input_type -> core.ReportZipFailedRequest
	19, // 14: core.CoreService.ReportBotUnauthorized:input_type -> core.ReportBotUnauthorizedRequest
	20, // 15: core.CoreService.ReportEmergencyCleanup:input_type -> core.ReportEmergencyCleanupRequest
	1,  // 16: core.CoreService.CheckDiskSpace:input_type -> core.Empty
	22, // 17: core.CoreService.ReportCronStats:input_type -> core.ReportCronStatsRequest
	23, // 18: core.CoreService.VerifyFolderShare:input_type -> core.VerifyFolderShareRequest
	1,  // 19: core.CoreService.Ping:input_type -> core.Empty
	5,  // 20: core.CoreService.ReportChunkResults:output_type -> core.ReportChunkResultsResponse
	8,  // 21: core.CoreService.GetFileMetadata:output_type -> core.FileMetadata
	11, // 22: core.CoreService.BatchCheckChunkStatus:output_type -> core.BatchCheckResponse
	1,  // 23: core.CoreService.ReportUploadFailed:output_type -> core.Empty
	1,  // 24: core.CoreService.ReportDeleteSuccess:output_type -> core.Empty
	1,  // 25: core.CoreService.ReportDeleteFailed:output_type -> core.Empty
	1,  // 26: core.CoreService.ReportFileCorrupted:output_type -> core.Empty
	1,  // 27: core.CoreService.ReportZipReady:output_type -> core.Empty
	1,  // 28: core.CoreService.ReportZipFailed:output_type -> core.Empty
	1,  // 29: core.CoreService.ReportBotUnauthorized:output_type -> core.Empty
	1,  // 30: core.CoreService.ReportEmergencyCleanup:output_type -> core.Empty
	21, // 31: core.CoreService.CheckDiskSpace:output_type -> core.DiskSpaceResponse
	1,  // 32: core.CoreService.ReportCronStats:output_type -> core.Empty
	24, // 33: core.CoreService.VerifyFolderShare:output_type -> core.VerifyFolderShareResponse
	2,  // 34: core.CoreService.Ping:output_type -> core.Pong
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		EnumInfos:         file_core_proto_enumTypes,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
