// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: core.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_ReportChunkResults_FullMethodName     = "/core.CoreService/ReportChunkResults"
	CoreService_ReportFileComplete_FullMethodName     = "/core.CoreService/ReportFileComplete"
	CoreService_GetFileMetadata_FullMethodName        = "/core.CoreService/GetFileMetadata"
	CoreService_CollectZipEntries_FullMethodName      = "/core.CoreService/CollectZipEntries"
	CoreService_ReportZipProgress_FullMethodName      = "/core.CoreService/ReportZipProgress"
	CoreService_BatchCheckChunkStatus_FullMethodName  = "/core.CoreService/BatchCheckChunkStatus"
	CoreService_ReportBandwidthUsage_FullMethodName   = "/core.CoreService/ReportBandwidthUsage"
	CoreService_ReportUploadFailed_FullMethodName     = "/core.CoreService/ReportUploadFailed"
	CoreService_ReportDeleteSuccess_FullMethodName    = "/core.CoreService/ReportDeleteSuccess"
	CoreService_ReportDeleteFailed_FullMethodName     = "/core.CoreService/ReportDeleteFailed"
	CoreService_ReportFileCorrupted_FullMethodName    = "/core.CoreService/ReportFileCorrupted"
	CoreService_ReportZipReady_FullMethodName         = "/core.CoreService/ReportZipReady"
	CoreService_ReportZipFailed_FullMethodName        = "/core.CoreService/ReportZipFailed"
	CoreService_ReportBotUnauthorized_FullMethodName  = "/core.CoreService/ReportBotUnauthorized"
	CoreService_ReportEmergencyCleanup_FullMethodName = "/core.CoreService/ReportEmergencyCleanup"
	CoreService_CheckDiskSpace_FullMethodName         = "/core.CoreService/CheckDiskSpace"
	CoreService_ReportCronStats_FullMethodName        = "/core.CoreService/ReportCronStats"
	CoreService_VerifyFolderShare_FullMethodName      = "/core.CoreService/VerifyFolderShare"
	CoreService_Ping_FullMethodName                   = "/core.CoreService/Ping"
	CoreService_GetS3Credential_FullMethodName        = "/core.CoreService/GetS3Credential"
	CoreService_ResolveS3Object_FullMethodName        = "/core.CoreService/ResolveS3Object"
	CoreService_PrepareS3Put_FullMethodName           = "/core.CoreService/PrepareS3Put"
	CoreService_ReportS3PutComplete_FullMethodName    = "/core.CoreService/ReportS3PutComplete"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreServiceClient interface {
	ReportChunkResults(ctx context.Context, in *ReportChunkResultsRequest, opts ...grpc.CallOption) (*ReportChunkResultsResponse, error)
	ReportFileComplete(ctx context.Context, in *ReportFileCompleteRequest, opts ...grpc.CallOption) (*Empty, error)
	GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*FileMetadata, error)
	CollectZipEntries(ctx context.Context, in *CollectZipEntriesRequest, opts ...grpc.CallOption) (*CollectZipEntriesResponse, error)
	ReportZipProgress(ctx context.Context, in *ReportZipProgressRequest, opts ...grpc.CallOption) (*Empty, error)
	BatchCheckChunkStatus(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error)
	ReportBandwidthUsage(ctx context.Context, in *ReportBandwidthUsageRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportUploadFailed(ctx context.Context, in *ReportUploadFailedRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportDeleteSuccess(ctx context.Context, in *ReportDeleteSuccessRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportDeleteFailed(ctx context.Context, in *ReportDeleteFailedRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportFileCorrupted(ctx context.Context, in *ReportFileCorruptedRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportZipReady(ctx context.Context, in *ReportZipReadyRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportZipFailed(ctx context.Context, in *ReportZipFailedRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportBotUnauthorized(ctx context.Context, in *ReportBotUnauthorizedRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportEmergencyCleanup(ctx context.Context, in *ReportEmergencyCleanupRequest, opts ...grpc.CallOption) (*Empty, error)
	CheckDiskSpace(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiskSpaceResponse, error)
	ReportCronStats(ctx context.Context, in *ReportCronStatsRequest, opts ...grpc.CallOption) (*Empty, error)
	VerifyFolderShare(ctx context.Context, in *VerifyFolderShareRequest, opts ...grpc.CallOption) (*VerifyFolderShareResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
	// S3 data-plane support (Phase D — Go-owned SigV4 + body I/O)
	GetS3Credential(ctx context.Context, in *GetS3CredentialRequest, opts ...grpc.CallOption) (*GetS3CredentialResponse, error)
	ResolveS3Object(ctx context.Context, in *ResolveS3ObjectRequest, opts ...grpc.CallOption) (*ResolveS3ObjectResponse, error)
	PrepareS3Put(ctx context.Context, in *PrepareS3PutRequest, opts ...grpc.CallOption) (*PrepareS3PutResponse, error)
	ReportS3PutComplete(ctx context.Context, in *ReportS3PutCompleteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) ReportChunkResults(ctx context.Context, in *ReportChunkResultsRequest, opts ...grpc.CallOption) (*ReportChunkResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportChunkResultsResponse)
	err := c.cc.Invoke(ctx, CoreService_ReportChunkResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportFileComplete(ctx context.Context, in *ReportFileCompleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportFileComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*FileMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileMetadata)
	err := c.cc.Invoke(ctx, CoreService_GetFileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) CollectZipEntries(ctx context.Context, in *CollectZipEntriesRequest, opts ...grpc.CallOption) (*CollectZipEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectZipEntriesResponse)
	err := c.cc.Invoke(ctx, CoreService_CollectZipEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportZipProgress(ctx context.Context, in *ReportZipProgressRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportZipProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) BatchCheckChunkStatus(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckResponse)
	err := c.cc.Invoke(ctx, CoreService_BatchCheckChunkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportBandwidthUsage(ctx context.Context, in *ReportBandwidthUsageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportBandwidthUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportUploadFailed(ctx context.Context, in *ReportUploadFailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportUploadFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportDeleteSuccess(ctx context.Context, in *ReportDeleteSuccessRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportDeleteSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportDeleteFailed(ctx context.Context, in *ReportDeleteFailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportDeleteFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportFileCorrupted(ctx context.Context, in *ReportFileCorruptedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportFileCorrupted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportZipReady(ctx context.Context, in *ReportZipReadyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportZipReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportZipFailed(ctx context.Context, in *ReportZipFailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportZipFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportBotUnauthorized(ctx context.Context, in *ReportBotUnauthorizedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportBotUnauthorized_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportEmergencyCleanup(ctx context.Context, in *ReportEmergencyCleanupRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportEmergencyCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) CheckDiskSpace(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiskSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskSpaceResponse)
	err := c.cc.Invoke(ctx, CoreService_CheckDiskSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportCronStats(ctx context.Context, in *ReportCronStatsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportCronStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) VerifyFolderShare(ctx context.Context, in *VerifyFolderShareRequest, opts ...grpc.CallOption) (*VerifyFolderShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyFolderShareResponse)
	err := c.cc.Invoke(ctx, CoreService_VerifyFolderShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, CoreService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetS3Credential(ctx context.Context, in *GetS3CredentialRequest, opts ...grpc.CallOption) (*GetS3CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetS3CredentialResponse)
	err := c.cc.Invoke(ctx, CoreService_GetS3Credential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ResolveS3Object(ctx context.Context, in *ResolveS3ObjectRequest, opts ...grpc.CallOption) (*ResolveS3ObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveS3ObjectResponse)
	err := c.cc.Invoke(ctx, CoreService_ResolveS3Object_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) PrepareS3Put(ctx context.Context, in *PrepareS3PutRequest, opts ...grpc.CallOption) (*PrepareS3PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareS3PutResponse)
	err := c.cc.Invoke(ctx, CoreService_PrepareS3Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReportS3PutComplete(ctx context.Context, in *ReportS3PutCompleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_ReportS3PutComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
type CoreServiceServer interface {
	ReportChunkResults(context.Context, *ReportChunkResultsRequest) (*ReportChunkResultsResponse, error)
	ReportFileComplete(context.Context, *ReportFileCompleteRequest) (*Empty, error)
	GetFileMetadata(context.Context, *GetFileMetadataRequest) (*FileMetadata, error)
	CollectZipEntries(context.Context, *CollectZipEntriesRequest) (*CollectZipEntriesResponse, error)
	ReportZipProgress(context.Context, *ReportZipProgressRequest) (*Empty, error)
	BatchCheckChunkStatus(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error)
	ReportBandwidthUsage(context.Context, *ReportBandwidthUsageRequest) (*Empty, error)
	ReportUploadFailed(context.Context, *ReportUploadFailedRequest) (*Empty, error)
	ReportDeleteSuccess(context.Context, *ReportDeleteSuccessRequest) (*Empty, error)
	ReportDeleteFailed(context.Context, *ReportDeleteFailedRequest) (*Empty, error)
	ReportFileCorrupted(context.Context, *ReportFileCorruptedRequest) (*Empty, error)
	ReportZipReady(context.Context, *ReportZipReadyRequest) (*Empty, error)
	ReportZipFailed(context.Context, *ReportZipFailedRequest) (*Empty, error)
	ReportBotUnauthorized(context.Context, *ReportBotUnauthorizedRequest) (*Empty, error)
	ReportEmergencyCleanup(context.Context, *ReportEmergencyCleanupRequest) (*Empty, error)
	CheckDiskSpace(context.Context, *Empty) (*DiskSpaceResponse, error)
	ReportCronStats(context.Context, *ReportCronStatsRequest) (*Empty, error)
	VerifyFolderShare(context.Context, *VerifyFolderShareRequest) (*VerifyFolderShareResponse, error)
	Ping(context.Context, *Empty) (*Pong, error)
	// S3 data-plane support (Phase D — Go-owned SigV4 + body I/O)
	GetS3Credential(context.Context, *GetS3CredentialRequest) (*GetS3CredentialResponse, error)
	ResolveS3Object(context.Context, *ResolveS3ObjectRequest) (*ResolveS3ObjectResponse, error)
	PrepareS3Put(context.Context, *PrepareS3PutRequest) (*PrepareS3PutResponse, error)
	ReportS3PutComplete(context.Context, *ReportS3PutCompleteRequest) (*Empty, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) ReportChunkResults(context.Context, *ReportChunkResultsRequest) (*ReportChunkResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportChunkResults not implemented")
}
func (UnimplementedCoreServiceServer) ReportFileComplete(context.Context, *ReportFileCompleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFileComplete not implemented")
}
func (UnimplementedCoreServiceServer) GetFileMetadata(context.Context, *GetFileMetadataRequest) (*FileMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedCoreServiceServer) CollectZipEntries(context.Context, *CollectZipEntriesRequest) (*CollectZipEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectZipEntries not implemented")
}
func (UnimplementedCoreServiceServer) ReportZipProgress(context.Context, *ReportZipProgressRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportZipProgress not implemented")
}
func (UnimplementedCoreServiceServer) BatchCheckChunkStatus(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCheckChunkStatus not implemented")
}
func (UnimplementedCoreServiceServer) ReportBandwidthUsage(context.Context, *ReportBandwidthUsageRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBandwidthUsage not implemented")
}
func (UnimplementedCoreServiceServer) ReportUploadFailed(context.Context, *ReportUploadFailedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUploadFailed not implemented")
}
func (UnimplementedCoreServiceServer) ReportDeleteSuccess(context.Context, *ReportDeleteSuccessRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDeleteSuccess not implemented")
}
func (UnimplementedCoreServiceServer) ReportDeleteFailed(context.Context, *ReportDeleteFailedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDeleteFailed not implemented")
}
func (UnimplementedCoreServiceServer) ReportFileCorrupted(context.Context, *ReportFileCorruptedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFileCorrupted not implemented")
}
func (UnimplementedCoreServiceServer) ReportZipReady(context.Context, *ReportZipReadyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportZipReady not implemented")
}
func (UnimplementedCoreServiceServer) ReportZipFailed(context.Context, *ReportZipFailedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportZipFailed not implemented")
}
func (UnimplementedCoreServiceServer) ReportBotUnauthorized(context.Context, *ReportBotUnauthorizedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBotUnauthorized not implemented")
}
func (UnimplementedCoreServiceServer) ReportEmergencyCleanup(context.Context, *ReportEmergencyCleanupRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEmergencyCleanup not implemented")
}
func (UnimplementedCoreServiceServer) CheckDiskSpace(context.Context, *Empty) (*DiskSpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDiskSpace not implemented")
}
func (UnimplementedCoreServiceServer) ReportCronStats(context.Context, *ReportCronStatsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCronStats not implemented")
}
func (UnimplementedCoreServiceServer) VerifyFolderShare(context.Context, *VerifyFolderShareRequest) (*VerifyFolderShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyFolderShare not implemented")
}
func (UnimplementedCoreServiceServer) Ping(context.Context, *Empty) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCoreServiceServer) GetS3Credential(context.Context, *GetS3CredentialRequest) (*GetS3CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetS3Credential not implemented")
}
func (UnimplementedCoreServiceServer) ResolveS3Object(context.Context, *ResolveS3ObjectRequest) (*ResolveS3ObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveS3Object not implemented")
}
func (UnimplementedCoreServiceServer) PrepareS3Put(context.Context, *PrepareS3PutRequest) (*PrepareS3PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareS3Put not implemented")
}
func (UnimplementedCoreServiceServer) ReportS3PutComplete(context.Context, *ReportS3PutCompleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportS3PutComplete not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_ReportChunkResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportChunkResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportChunkResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportChunkResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportChunkResults(ctx, req.(*ReportChunkResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportFileComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFileCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportFileComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportFileComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportFileComplete(ctx, req.(*ReportFileCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetFileMetadata(ctx, req.(*GetFileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_CollectZipEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectZipEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CollectZipEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_CollectZipEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CollectZipEntries(ctx, req.(*CollectZipEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportZipProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportZipProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportZipProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportZipProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportZipProgress(ctx, req.(*ReportZipProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_BatchCheckChunkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).BatchCheckChunkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_BatchCheckChunkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).BatchCheckChunkStatus(ctx, req.(*BatchCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportBandwidthUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBandwidthUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportBandwidthUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportBandwidthUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportBandwidthUsage(ctx, req.(*ReportBandwidthUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportUploadFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUploadFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportUploadFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportUploadFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportUploadFailed(ctx, req.(*ReportUploadFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportDeleteSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDeleteSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportDeleteSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportDeleteSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportDeleteSuccess(ctx, req.(*ReportDeleteSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportDeleteFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDeleteFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportDeleteFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportDeleteFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportDeleteFailed(ctx, req.(*ReportDeleteFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportFileCorrupted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFileCorruptedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportFileCorrupted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportFileCorrupted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportFileCorrupted(ctx, req.(*ReportFileCorruptedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportZipReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportZipReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportZipReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportZipReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportZipReady(ctx, req.(*ReportZipReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportZipFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportZipFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportZipFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportZipFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportZipFailed(ctx, req.(*ReportZipFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportBotUnauthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBotUnauthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportBotUnauthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportBotUnauthorized_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportBotUnauthorized(ctx, req.(*ReportBotUnauthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportEmergencyCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEmergencyCleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportEmergencyCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportEmergencyCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportEmergencyCleanup(ctx, req.(*ReportEmergencyCleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_CheckDiskSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CheckDiskSpace(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportCronStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCronStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportCronStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportCronStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportCronStats(ctx, req.(*ReportCronStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_VerifyFolderShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyFolderShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).VerifyFolderShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_VerifyFolderShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).VerifyFolderShare(ctx, req.(*VerifyFolderShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetS3Credential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetS3CredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetS3Credential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetS3Credential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetS3Credential(ctx, req.(*GetS3CredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ResolveS3Object_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveS3ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ResolveS3Object(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ResolveS3Object_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ResolveS3Object(ctx, req.(*ResolveS3ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_PrepareS3Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareS3PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).PrepareS3Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_PrepareS3Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).PrepareS3Put(ctx, req.(*PrepareS3PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReportS3PutComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportS3PutCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportS3PutComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportS3PutComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportS3PutComplete(ctx, req.(*ReportS3PutCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportChunkResults",
			Handler:    _CoreService_ReportChunkResults_Handler,
		},
		{
			MethodName: "ReportFileComplete",
			Handler:    _CoreService_ReportFileComplete_Handler,
		},
		{
			MethodName: "GetFileMetadata",
			Handler:    _CoreService_GetFileMetadata_Handler,
		},
		{
			MethodName: "CollectZipEntries",
			Handler:    _CoreService_CollectZipEntries_Handler,
		},
		{
			MethodName: "ReportZipProgress",
			Handler:    _CoreService_ReportZipProgress_Handler,
		},
		{
			MethodName: "BatchCheckChunkStatus",
			Handler:    _CoreService_BatchCheckChunkStatus_Handler,
		},
		{
			MethodName: "ReportBandwidthUsage",
			Handler:    _CoreService_ReportBandwidthUsage_Handler,
		},
		{
			MethodName: "ReportUploadFailed",
			Handler:    _CoreService_ReportUploadFailed_Handler,
		},
		{
			MethodName: "ReportDeleteSuccess",
			Handler:    _CoreService_ReportDeleteSuccess_Handler,
		},
		{
			MethodName: "ReportDeleteFailed",
			Handler:    _CoreService_ReportDeleteFailed_Handler,
		},
		{
			MethodName: "ReportFileCorrupted",
			Handler:    _CoreService_ReportFileCorrupted_Handler,
		},
		{
			MethodName: "ReportZipReady",
			Handler:    _CoreService_ReportZipReady_Handler,
		},
		{
			MethodName: "ReportZipFailed",
			Handler:    _CoreService_ReportZipFailed_Handler,
		},
		{
			MethodName: "ReportBotUnauthorized",
			Handler:    _CoreService_ReportBotUnauthorized_Handler,
		},
		{
			MethodName: "ReportEmergencyCleanup",
			Handler:    _CoreService_ReportEmergencyCleanup_Handler,
		},
		{
			MethodName: "CheckDiskSpace",
			Handler:    _CoreService_CheckDiskSpace_Handler,
		},
		{
			MethodName: "ReportCronStats",
			Handler:    _CoreService_ReportCronStats_Handler,
		},
		{
			MethodName: "VerifyFolderShare",
			Handler:    _CoreService_VerifyFolderShare_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CoreService_Ping_Handler,
		},
		{
			MethodName: "GetS3Credential",
			Handler:    _CoreService_GetS3Credential_Handler,
		},
		{
			MethodName: "ResolveS3Object",
			Handler:    _CoreService_ResolveS3Object_Handler,
		},
		{
			MethodName: "PrepareS3Put",
			Handler:    _CoreService_PrepareS3Put_Handler,
		},
		{
			MethodName: "ReportS3PutComplete",
			Handler:    _CoreService_ReportS3PutComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
