// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: transfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueBufferedUploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileId         string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	TempStorageKey string                 `protobuf:"bytes,2,opt,name=temp_storage_key,json=tempStorageKey,proto3" json:"temp_storage_key,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsChunk        bool                   `protobuf:"varint,4,opt,name=is_chunk,json=isChunk,proto3" json:"is_chunk,omitempty"`
	ChunkIndex     int32                  `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Size           int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueBufferedUploadRequest) Reset() {
	*x = EnqueueBufferedUploadRequest{}
	mi := &file_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBufferedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBufferedUploadRequest) ProtoMessage() {}

func (x *EnqueueBufferedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBufferedUploadRequest.ProtoReflect.Descriptor instead.
func (*EnqueueBufferedUploadRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueBufferedUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *EnqueueBufferedUploadRequest) GetTempStorageKey() string {
	if x != nil {
		return x.TempStorageKey
	}
	return ""
}

func (x *EnqueueBufferedUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnqueueBufferedUploadRequest) GetIsChunk() bool {
	if x != nil {
		return x.IsChunk
	}
	return false
}

func (x *EnqueueBufferedUploadRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *EnqueueBufferedUploadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type EnqueueBufferedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBufferedUploadResponse) Reset() {
	*x = EnqueueBufferedUploadResponse{}
	mi := &file_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBufferedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBufferedUploadResponse) ProtoMessage() {}

func (x *EnqueueBufferedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBufferedUploadResponse.ProtoReflect.Descriptor instead.
func (*EnqueueBufferedUploadResponse) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueBufferedUploadResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EnqueueBufferedUploadResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TransferPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPingRequest) Reset() {
	*x = TransferPingRequest{}
	mi := &file_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPingRequest) ProtoMessage() {}

func (x *TransferPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPingRequest.ProtoReflect.Descriptor instead.
func (*TransferPingRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{2}
}

type TransferPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPingResponse) Reset() {
	*x = TransferPingResponse{}
	mi := &file_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPingResponse) ProtoMessage() {}

func (x *TransferPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPingResponse.ProtoReflect.Descriptor instead.
func (*TransferPingResponse) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *TransferPingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FlushAndConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushAndConfirmRequest) Reset() {
	*x = FlushAndConfirmRequest{}
	mi := &file_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushAndConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushAndConfirmRequest) ProtoMessage() {}

func (x *FlushAndConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushAndConfirmRequest.ProtoReflect.Descriptor instead.
func (*FlushAndConfirmRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *FlushAndConfirmRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ChunkConfirmation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex        int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TelegramFileId    string                 `protobuf:"bytes,2,opt,name=telegram_file_id,json=telegramFileId,proto3" json:"telegram_file_id,omitempty"`
	TelegramMessageId int32                  `protobuf:"varint,3,opt,name=telegram_message_id,json=telegramMessageId,proto3" json:"telegram_message_id,omitempty"`
	BotId             int64                  `protobuf:"varint,4,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	EncryptionIv      string                 `protobuf:"bytes,5,opt,name=encryption_iv,json=encryptionIv,proto3" json:"encryption_iv,omitempty"`
	Size              int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Etag              string                 `protobuf:"bytes,7,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChunkConfirmation) Reset() {
	*x = ChunkConfirmation{}
	mi := &file_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkConfirmation) ProtoMessage() {}

func (x *ChunkConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkConfirmation.ProtoReflect.Descriptor instead.
func (*ChunkConfirmation) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkConfirmation) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkConfirmation) GetTelegramFileId() string {
	if x != nil {
		return x.TelegramFileId
	}
	return ""
}

func (x *ChunkConfirmation) GetTelegramMessageId() int32 {
	if x != nil {
		return x.TelegramMessageId
	}
	return 0
}

func (x *ChunkConfirmation) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *ChunkConfirmation) GetEncryptionIv() string {
	if x != nil {
		return x.EncryptionIv
	}
	return ""
}

func (x *ChunkConfirmation) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkConfirmation) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type FlushAndConfirmResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllComplete     bool                   `protobuf:"varint,1,opt,name=all_complete,json=allComplete,proto3" json:"all_complete,omitempty"`
	TotalChunks     int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	CompletedChunks int32                  `protobuf:"varint,3,opt,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty"`
	Chunks          []*ChunkConfirmation   `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Chunks the client has handed off to Go = already-in-DB (completed) plus
	// still-draining (queued/in-flight). Lets NestJS tell "client sent everything,
	// background still uploading" (→ buffer & return OK) apart from "client never
	// sent some chunk" (→ reject).
	ReceivedChunks int32 `protobuf:"varint,5,opt,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	AllReceived    bool  `protobuf:"varint,6,opt,name=all_received,json=allReceived,proto3" json:"all_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushAndConfirmResponse) Reset() {
	*x = FlushAndConfirmResponse{}
	mi := &file_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushAndConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushAndConfirmResponse) ProtoMessage() {}

func (x *FlushAndConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushAndConfirmResponse.ProtoReflect.Descriptor instead.
func (*FlushAndConfirmResponse) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *FlushAndConfirmResponse) GetAllComplete() bool {
	if x != nil {
		return x.AllComplete
	}
	return false
}

func (x *FlushAndConfirmResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FlushAndConfirmResponse) GetCompletedChunks() int32 {
	if x != nil {
		return x.CompletedChunks
	}
	return 0
}

func (x *FlushAndConfirmResponse) GetChunks() []*ChunkConfirmation {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *FlushAndConfirmResponse) GetReceivedChunks() int32 {
	if x != nil {
		return x.ReceivedChunks
	}
	return 0
}

func (x *FlushAndConfirmResponse) GetAllReceived() bool {
	if x != nil {
		return x.AllReceived
	}
	return false
}

var File_transfer_proto protoreflect.FileDescriptor

const file_transfer_proto_rawDesc = "" +
	"\n" +
	"\x0etransfer.proto\x12\btransfer\"\xca\x01\n" +
	"\x1cEnqueueBufferedUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12(\n" +
	"\x10temp_storage_key\x18\x02 \x01(\tR\x0etempStorageKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bis_chunk\x18\x04 \x01(\bR\aisChunk\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"S\n" +
	"\x1dEnqueueBufferedUploadResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13TransferPingRequest\"4\n" +
	"\x14TransferPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"1\n" +
	"\x16FlushAndConfirmRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\xf2\x01\n" +
	"\x11ChunkConfirmation\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12(\n" +
	"\x10telegram_file_id\x18\x02 \x01(\tR\x0etelegramFileId\x12.\n" +
	"\x13telegram_message_id\x18\x03 \x01(\x05R\x11telegramMessageId\x12\x15\n" +
	"\x06bot_id\x18\x04 \x01(\x03R\x05botId\x12#\n" +
	"\rencryption_iv\x18\x05 \x01(\tR\fencryptionIv\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04size\x12\x12\n" +
	"\x04etag\x18\a \x01(\tR\x04etag\"\x8b\x02\n" +
	"\x17FlushAndConfirmResponse\x12!\n" +
	"\fall_complete\x18\x01 \x01(\bR\vallComplete\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x12)\n" +
	"\x10completed_chunks\x18\x03 \x01(\x05R\x0fcompletedChunks\x123\n" +
	"\x06chunks\x18\x04 \x03(\v2\x1b.transfer.ChunkConfirmationR\x06chunks\x12'\n" +
	"\x0freceived_chunks\x18\x05 \x01(\x05R\x0ereceivedChunks\x12!\n" +
	"\fall_received\x18\x06 \x01(\bR\vallReceived2\x9a\x02\n" +
	"\x0fTransferService\x12V\n" +
	"\x0fFlushAndConfirm\x12 .transfer.FlushAndConfirmRequest\x1a!.transfer.FlushAndConfirmResponse\x12h\n" +
	"\x15EnqueueBufferedUpload\x12&.transfer.EnqueueBufferedUploadRequest\x1a'.transfer.EnqueueBufferedUploadResponse\x12E\n" +
	"\x04Ping\x12\x1d.transfer.TransferPingRequest\x1a\x1e.transfer.TransferPingResponseBGZEgithub.com/realldz/tele-drive/backend-transfer-go/internal/grpc/protob\x06proto3"

var (
	file_transfer_proto_rawDescOnce sync.Once
	file_transfer_proto_rawDescData []byte
)

func file_transfer_proto_rawDescGZIP() []byte {
	file_transfer_proto_rawDescOnce.Do(func() {
		file_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_proto_rawDesc), len(file_transfer_proto_rawDesc)))
	})
	return file_transfer_proto_rawDescData
}

var file_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_transfer_proto_goTypes = []any{
	(*EnqueueBufferedUploadRequest)(nil),  // 0: transfer.EnqueueBufferedUploadRequest
	(*EnqueueBufferedUploadResponse)(nil), // 1: transfer.EnqueueBufferedUploadResponse
	(*TransferPingRequest)(nil),           // 2: transfer.TransferPingRequest
	(*TransferPingResponse)(nil),          // 3: transfer.TransferPingResponse
	(*FlushAndConfirmRequest)(nil),        // 4: transfer.FlushAndConfirmRequest
	(*ChunkConfirmation)(nil),             // 5: transfer.ChunkConfirmation
	(*FlushAndConfirmResponse)(nil),       // 6: transfer.FlushAndConfirmResponse
}
var file_transfer_proto_depIdxs = []int32{
	5, // 0: transfer.FlushAndConfirmResponse.chunks:type_name -> transfer.ChunkConfirmation
	4, // 1: transfer.TransferService.FlushAndConfirm:input_type -> transfer.FlushAndConfirmRequest
	0, // 2: transfer.TransferService.EnqueueBufferedUpload:input_type -> transfer.EnqueueBufferedUploadRequest
	2, // 3: transfer.TransferService.Ping:input_type -> transfer.TransferPingRequest
	6, // 4: transfer.TransferService.FlushAndConfirm:output_type -> transfer.FlushAndConfirmResponse
	1, // 5: transfer.TransferService.EnqueueBufferedUpload:output_type -> transfer.EnqueueBufferedUploadResponse
	3, // 6: transfer.TransferService.Ping:output_type -> transfer.TransferPingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transfer_proto_init() }
func file_transfer_proto_init() {
	if File_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_proto_rawDesc), len(file_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_proto_goTypes,
		DependencyIndexes: file_transfer_proto_depIdxs,
		MessageInfos:      file_transfer_proto_msgTypes,
	}.Build()
	File_transfer_proto = out.File
	file_transfer_proto_goTypes = nil
	file_transfer_proto_depIdxs = nil
}
